FROM node:23

WORKDIR /app

# Copier les fichiers de dépendances
COPY ./frontend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des sources
COPY ./frontend .

# Exposer le port
EXPOSE 8080

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]