FROM node:23

WORKDIR /app

# Copier les fichiers de dépendances
COPY ./panelAdmin/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des sources
COPY ./panelAdmin .

# Exposer le port
EXPOSE 8081

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]